export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  TEAM: '/team',
  STORIES: '/stories',
  PROGRAMMES_DISCOVERY: '/programmes/discovery',
  PROGRAMMES_ACCELERATOR: '/programmes/accelerator',
  PROGRAMMES_MENTORSHIP: '/programmes/mentorship',
  OPPORTUNITIES: '/opportunities',
  FOR_ORGANISATIONS: '/for-organisations',
  CONTACT: '/contact',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  SIGN_IN: '/signin',
  FOR_YOUNG_PEOPLE: '/for-young-people',
  FOR_SCHOOLS: '/for-schools',
  PROGRAMMES_CAREER_ACCELERATORS: '/programmes/career-accelerators',
  PROGRAMMES_MICRO_OPPORTUNITIES: '/programmes/micro-opportunities',
  ASSESSMENT: '/assessment',
  FOR_SCHOOLS_PARTNERSHIPS: '/for-schools/partnerships',
  FOR_SCHOOLS_PROFESSIONAL_DEVELOPMENT: '/for-schools/professional-development',
  FOR_ORGANISATIONS_CREATE_OPPORTUNITIES: '/for-organisations/create-opportunities',
  FOR_ORGANISATIONS_PARTNERSHIPS: '/for-organisations/partnerships',
};
